#!/usr/bin/env zsh

echo "\n<<< Starting Node Setup >>> \n"

if exists node; then
	echo "Node $(node --version) and NPM $(npm --version) already exists, skipping install"
else
	echo "Installing Node and NPM with n..."
	n latest
fi
