#!/usr/bin/env zsh

if grep -Fxq '/opt/homebrew/bin/zsh' '/etc/shells'; then
  echo '/opt/homebrew/bin/zsh already exists in /etc/shells'
else
  echo "Enter sudo password to append homebrew installed zsh to /etc/shells"
  echo '/opt/homebrew/bin/zsh' | sudo tee -a '/etc/shells' >/dev/null
fi

if [ "$SHELL" = '/opt/homebrew/bin/zsh' ]; then
  echo '$SHELL is already the hiomebrew installed zsh'
else
  echo "Enter user password to change login shell to homebrew installed zsh"
  chsh -s '/opt/homebrew/bin/zsh'
fi
